### ISSUE TITLE
Generated OpenAPI schema should support nullable `enum`s

### ISSUE THREAD

**Issue by kbighorse** [bullet-train-co/bullet_train#1145]
Steps to reproduce:
- define `enum` in model:
```
  enum status: {
    status1: 1,
    status2: 2,
    status3: 3,
  }
```
- leave field unassigned in test factories
- run `<root>/test/controllers/api/open_api_controller_test.rb`

Expected result:
- openapi.yaml:
```
        status:
          type:
          - string
          - 'null'
          nullable: true
          enum:
          - status1
          - status2
          - status3
          - null
          description: Some Status
```
- test passes

Actual result:
- test output:
```
Example value must conform to the schema: `status` property must be equal to one of the allowed values "status1", "status2", "status3".

Did you mean:
  - status1
  - status2
  - status3

...

Warning was generated by the no-invalid-media-type-examples rule.
```
- openapi.yaml:
```
        status:
          type:
          - string
          - 'null'
          enum:
          - status1
          - status2
          - status3
          description: Some Status
```
The OpenAPI spec requires that `enum`s be explicitly nullable:
https://swagger.io/docs/specification/data-models/enums/
