### ISSUE TITLE
Super Scaffolding adds "Event" model to roles.yml twice.

### ISSUE THREAD

**Issue by brennanlawrence** [bullet-train-co/bullet_train#25]
```
config/models/roles.yml

default:
  models:
    Task: read
    Event: read
    Event: read
...
admin:
  ...
  models:
    Task: manage
    Event: manage
    Event: manage
...
```

It seems to be associated with the word "Event".
