### ISSUE TITLE
Create CircleCI orb to use across all packages

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train#275]
If possible, it might help to [make an orb of our own](https://circleci.com/docs/2.0/orb-author-intro) which clones the starter repository and takes care of all necessary setup before running tests since we're starting to get duplicated code in our CircleCI configs.

For example, the [orbs commands](https://circleci.com/docs/2.0/orb-concepts#commands) docs shows how to run individual commands for an orb (`- aws-s3/copy` below):
```yml
version: 2.1

orbs:
  aws-s3: circleci/aws-s3@x.y.z

jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      # using the aws-s3 orb's "copy" command.
      - aws-s3/copy:
          from: bucket/build_asset.txt
          to: 's3://my-s3-bucket-name'

  #... workflows , other jobs etc.
```

It might help to isolate our concerns there and just call the custom orb commands in each individual package.

**Comment by gazayas** [comment]
[Publishing Orbs](https://circleci.com/docs/2.0/creating-orbs)

**Comment by gazayas** [comment]
Got the Standard Ruby check to work, planning on working on caches and the Minitest suite next.

**Comment by gazayas** [comment]
@andrewculver I made more progress on this one, and you can see over in [this PR](https://github.com/bullet-train-co/bullet_train-themes-light/pull/32) in my forked `bullet_train-themes-light` repo that the tests are passing using the following commands.

## `bullet_train_testing` commands
### For Standard Ruby
```yml
- bullet_train_testing/standard_ruby
```

### For the Starter Repo Minitest
```yml
- bullet_train_testing/starter_repo_minitest:
    packageName: bullet_train-themes-light
    knapsackPro: false
```

### For the Starter Repo Super Scaffolding tests:
```yml
- bullet_train_testing/starter_repo_super_scaffolding:
    packageName: bullet_train-themes-light
    knapsackPro: false
```

## paralellism
To run the tests in paralellel, you can change, for example, the Starter Repo Minitest to the following:
```yml
- bullet_train_testing/starter_repo_minitest:
    packageName: bullet_train-themes-light
    knapsackPro: true
    parallelism: 16
```

Since it's working for the most part, I'll leave the orb as is and move on to something else unless you'd like to move forward with it. In that case I can try to work the caching logic into it too, as well as anything else that would be helpful for our CircleCI tests.
