### ISSUE TITLE
Super scaffolding breaks roles.yml with improper indentation

### ISSUE THREAD

**Issue by jagthedrummer** [bullet-train-co/bullet_train#778]
I did this:

```
./bin/super-scaffold crud Billing::SubscriptionExtension Team extension_team_id:super_select{class_name=Team} --trace
```

And got this output:

```
Writing './app/controllers/account/billing/subscription_extensions_controller.rb'.
Fixing Standard Ruby on './app/controllers/account/billing/subscription_extensions_controller.rb'.
Writing './app/views/account/billing/subscription_extensions/index.html.erb'.
Writing './app/views/account/billing/subscription_extensions/_menu_item.html.erb'.
Writing './app/views/account/billing/subscription_extensions/_index.html.erb'.
Writing './app/views/account/billing/subscription_extensions/_subscription_extension.html.erb'.
Writing './app/views/account/billing/subscription_extensions/edit.html.erb'.
Writing './app/views/account/billing/subscription_extensions/show.html.erb'.
Writing './app/views/account/billing/subscription_extensions/_form.html.erb'.
Writing './app/views/account/billing/subscription_extensions/new.html.erb'.
Writing './app/views/account/billing/subscription_extensions/_breadcrumbs.html.erb'.
Proceeding to generate './app/views/api/v1/billing/subscription_extensions'.
Writing './app/views/api/v1/billing/subscription_extensions/_subscription_extension.json.jbuilder'.
Writing './app/views/api/v1/billing/subscription_extensions/index.json.jbuilder'.
Writing './app/views/api/v1/billing/subscription_extensions/show.json.jbuilder'.
Writing './config/locales/en/billing/subscription_extensions.en.yml'.
Writing './app/controllers/api/v1/billing/subscription_extensions_controller.rb'.
Fixing Standard Ruby on './app/controllers/api/v1/billing/subscription_extensions_controller.rb'.
Writing './test/controllers/api/v1/billing/subscription_extensions_controller_test.rb'.
Fixing Standard Ruby on './test/controllers/api/v1/billing/subscription_extensions_controller_test.rb'.
Updating './test/factories/billing/subscription_extensions.rb'.
Updating './app/models/team.rb'.
rake aborted!
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 4 column 9
<internal:/Users/jgreen/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/jgreen/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Tasks: TOP => bullet_train:super_scaffolding
(See full trace by running task with --trace)
```

Adding `--trace` didn't get me any additional info.

I _finally_ traced the issue down to the fact that the first few lines of `roles.yml` had been updated to this:

```yml
default: # AKA : listener
  models:
  Billing::SubscriptionExtension: read
```

Instead of this:

```yml
default: # AKA : listener
  models:
    Billing::SubscriptionExtension: read
```

I corrected the indentation and then re-ran the scaffolding command and then the rest of the scaffolding process seemed to work.

**Comment by gazayas** [comment]
Strange, the indentation is working for me 🤔 Can I ask what you wrote for `rails g model`?

**Comment by jagthedrummer** [comment]
I think it was something like `rails g model Billing::SubscriptionExtension team:references extension_team:references`.

**Comment by gazayas** [comment]
Looked over this one again today, can't seem to reproduce... I don't want to close it though if it really is a problem, so I think I'll leave this one be until we can pin down what the actual issue is.

If anything, the only thing that comes to mind is the `BlockManipulator` and how we've changed the indentation logic in the past. Will consider looking into that if we make any progress.

**Comment by jagthedrummer** [comment]
I just tested this again and it has something to do with the comment on the first line. With no trailing comment everything works as expected, but a trailing comment on either of the first to lines causes different problems.

With this I get the error and broken indentation described in the original issue.

```yaml
default: # test
  models:
    Team: read
```

With this there's no error thrown, but the new model ends up being added in the wrong spot.

```yaml
default:
  models: # test
    Team: read
```

Instead of the new model being added under `default.models` it's added under `editor.models`.

```yaml
default:
  models: # test
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Billing::SubscriptionExtension: read
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    Billing::SubscriptionExtension: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
```
